# Generated by Django 5.1.5 on 2025-02-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('casa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uno_a_uno.casa')),
                ('nombre', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=11)),
                ('celular', models.IntegerField(default=53271799)),
            ],
        ),
    ]
