# Generated by Django 5.1.6 on 2025-02-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("pasaporte", models.CharField(max_length=10)),
                ("mail", models.EmailField(max_length=254)),
                ("pais", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Disponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("habitaciones", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("fecha_entrada", models.DateField()),
                ("fecha_salida", models.DateField()),
                ("cant_habitaciones", models.IntegerField()),
                ("cant_personas", models.IntegerField()),
            ],
        ),
    ]
