# Generated by Django 5.1.1 on 2024-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('precio', models.FloatField(verbose_name='precio')),
                ('horario', models.CharField(max_length=100, verbose_name='horario')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
                ('deleted', models.DateTimeField(auto_now_add=True, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
