# Generated by Django 5.1.2 on 2024-10-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='deleted',
        ),
    ]
