# Generated by Django 5.1.5 on 2025-02-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Casa_Rodolfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rodolfo", models.CharField(max_length=50)),
                (
                    "cant_habitaciones",
                    models.IntegerField(blank=True, default=9, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocupadas", models.IntegerField(blank=True, null=True)),
                ("disponibles", models.IntegerField(blank=True, null=True)),
                ("fecha", models.DateField()),
                (
                    "nombre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uno_a_muchos.casa_rodolfo",
                    ),
                ),
            ],
        ),
    ]
