# Generated by Django 5.1.5 on 2025-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uno_a_muchos", "0002_rename_rodolfo_casa_rodolfo_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitaciones",
            name="disponible",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
