# Generated by Django 5.1.1 on 2024-12-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reservas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
