# Generated by Django 4.2.7 on 2024-12-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_servicio_servicio_delete_tienda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria_servicio',
            new_name='Categoria_producto',
        ),
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Producto',
        ),
        migrations.AlterModelOptions(
            name='categoria_producto',
            options={'verbose_name': 'categoria_producto', 'verbose_name_plural': 'categoria_producto'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
