# Generated by Django 5.1.1 on 2024-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('cliente', models.CharField(max_length=250, verbose_name='cliente')),
                ('cant_habit', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_entrada', models.DateField(verbose_name='fecha_entrada')),
                ('fecha_salida', models.DateField(verbose_name='fecha_salida')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
