# Generated by Django 5.1.1 on 2024-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_servicios_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(upload_to='servicios', verbose_name='imagen'),
        ),
    ]
