# Generated by Django 5.1.1 on 2024-12-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicios_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'servicios', 'verbose_name_plural': 'servicios'},
        ),
    ]
