# Generated by Django 5.1.6 on 2025-02-25 18:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=50, verbose_name="cliente")),
                ("correo", models.EmailField(max_length=250, verbose_name="correo")),
                (
                    "cant_habitaciones",
                    models.IntegerField(verbose_name="cant_habitaciones"),
                ),
                ("cant_dias", models.IntegerField(verbose_name="cant_dias")),
                ("pais", models.CharField(max_length=50, verbose_name="pais")),
                ("cena", models.BooleanField(null=True, verbose_name="cena")),
                ("desayuno", models.BooleanField(null=True, verbose_name="desayuno")),
                ("fecha_entrada", models.DateField(null=True)),
                ("fecha_salida", models.DateField(null=True)),
                ("cant_personas", models.IntegerField(verbose_name="cant_personas")),
                ("comentarios", models.TextField(verbose_name="comentarios")),
            ],
        ),
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("disponible", models.IntegerField(verbose_name="cantidad")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas.reserva",
                    ),
                ),
            ],
        ),
    ]
